### ISSUE TITLE
Use rule schemas

### ISSUE THREAD

**Issue by IanVS** [willklein/dryer#14]
Now that ESLint has added rule schemas in https://github.com/eslint/eslint/pull/2580 (documented in http://eslint.org/docs/developer-guide/working-with-rules#options-schemas), would it be possible to use those in determining which options are a best fit?

**Comment by willklein** [comment]
Yes! That's actually what #1 is about. @gyandeeps pointed this out to me in the ESLint gitter chat, schemas had just been added and I realized they were exactly what we need for this. I'm going to mark this as a duplicate and close it.
